### ISSUE TITLE
Wrong return value decoding

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aesophia#306] opened 2021-04-13 17:27 UTC
Not sure on which end this issue is located, but for 
```
    entrypoint return_zero() : int =
        0
```

I'm getting `returnValue : cb_ABQG4Fg=` which the JS-SDK translates to `"false"` , can somebody take a look please?

**Comment by davidyuk** [comment] 2021-04-14 01:04
Seems that I can't reproduce this issue using the current develop version of sdk:
```js
const { Universal, Node, MemoryAccount } = require('./dist/aepp-sdk');

const code = `
contract Identity =
  entrypoint return_zero() : int =
    0
`;

(async () => {
  const sdk = await Universal({
    nodes: [
      { name: 'ae_uat', instance: await Node({ url: 'https://testnet.aeternity.io' }) },
    ],
    compilerUrl: 'https://compiler.aepps.com',
    accounts: [MemoryAccount({ keypair: {
      secretKey: 'bf66e1c256931870908a649572ed0257876bb84e3cdf71efb12f56c7335fad54d5cf08400e988222f26eb4b02c8f89077457467211a6e6d955edb70749c6a33b',
      publicKey: 'ak_2dATVcZ9KJU5a8hdsVtTv21pYiGWiPbmVcU1Pz72FFqpk9pSRR',
    } })],
  });

  const bytecode = await sdk.contractCompile(code);
  const deployed = await bytecode.deploy();
  const tx = await deployed.call('return_zero');
  console.log(await tx.decode())
})();
```
```
$  node test.js
cb_ABQG4Fg=
0
```

**Comment by marc0olo** [comment] 2021-06-08 15:29
@nikita-fuchs can this be closed? is this fixed now in aestudio, too?

**Closed** 2021-09-23 19:15 UTC
